name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install buildozer cython

    - name: Accept Android SDK Licenses
      uses: android-actions/setup-android@v3

    - name: Build with Buildozer
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update -y
        sudo apt-get install -y -qq libssl-dev libffi-dev python3-dev
        yes | buildozer android debug || true

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: RobiulBot-APK
        path: |
          bin/*.apk
          .buildozer/android/platform/build-*/dists/*/build/outputs/apk/*/*.apk
